stages:
  - test

golang_tests:
  stage: test
  image: golang:latest
  script:
    - uname -a
    - go version
    - go vet $(go list ./...)
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - staticcheck ./...
    - go test -v $(go list ./...)
    - go run cmd/perfcheck/perfcheck.go

trivy:
  stage: test
  image: curlimages/curl:latest
  script:
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
    - ./trivy fs .

# jobs run in test stage
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
