image: golang:latest

pipelines:
  default:
    - step:
        name: Check
        script:
          - go version
          - go test -v $(go list ./...)
          - go vet $(go list ./...)
          - go run cmd/perfcheck/perfcheck.go


