image: golang:latest

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - go version
            - mkdir test-reports
            - go get -u github.com/jstemmer/go-junit-report
            - go test $(go list ./...) -v 2>&1 | go-junit-report > test-reports/report.xml
            - go build src/*
            - go vet $(go list ./...)
            - go run cmd/perfcheck/perfcheck.go

      - step:
          name: Lint code
          image: golangci/golangci-lint:latest
          script:
            - golangci-lint run -v


