name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Run go commands on latest version
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.19.0'
      - run: uname -a
      - run: go version
      - run: go vet $(go list ./...)
      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: staticcheck ./...
      - run: go test -v $(go list ./...)
      - run: go run cmd/perfcheck/perfcheck.go
