name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: go version
      - run: go vet $(go list ./...)
      - run: go test -v $(go list ./...)
      - run: go run cmd/perfcheck/perfcheck.go
